import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const applefont1 = localfont({
  src: [
    {
      path: "../../public/font/sf-pro-display_semibold.woff2",
      weight: "500",
    },
  ],
  variable: "--font-applefont1",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${applefont1.variable}`}
        >{children}</body>
    </html>
  );
}
